import Head from 'next/head'
import styles from '../styles/Checkout.module.css'
import Link from 'next/link'
import axios from 'axios';
import cookieCutter from 'cookie-cutter'
import React, { useState, useEffect } from 'react'
import { Divider, Navbar, CartItem, BackToTopButton, MyInput, MyButton, TextWithLabel } from '../Components/MyComponents'
import { useRouter } from 'next/router'
export default function ConfirmOrder() {
    const [dataState, setDataState] = useState([]);
    const [userObj, setUserObj] = useState([]);
    const [gotData, setGotData] = useState(false);
    const [total, setTotal] = useState(0);

    const router = useRouter();

    var tempTotal = 0;
    useEffect(() => {
        getCookie();
    }, []);


    function getCookie() {
        var cookieVal = cookieCutter.get('Cart');
        var userData = sessionStorage.getItem('UserData');
        if (cookieVal && userData) {
            setDataState(JSON.parse(cookieVal));
            setUserObj(JSON.parse(userData));
            setGotData(true);
        }
    }
    function totalGot(e, i) {
        var current = parseInt(e);
        tempTotal = tempTotal + current;
        if (i == dataState.length - 1) {
            setTotal(tempTotal);
        }
    }

    function PlaceOrder() {
        setTimeout(() => {
            CreateNewUser();
        }, 500);
    }

    function CreateNewUser() {
        axios.post(`http://localhost:1000/addNewOrder`, {
            UserInfo: userObj,
            Order: dataState,
        }).then((response) => {
            if (response.status == 200) {
                alert("Order Added");
            }
            else {
                alert("Order not added, Try again later")
            }
        });
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Confirm</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar />
                <BackToTopButton />
                <Divider title="Confirm Order" />

                {gotData ?
                    <div className={styles.ConDiv}>
                        <div className={styles.FormCon}>
                            <h1 className={styles.FormConHeader}>Shipping Info</h1>
                            {userObj ?
                                <div className={styles.confirmInfoContainer}>
                                    <TextWithLabel label="Email:" text={userObj.email} />
                                    <div className={styles.rowDiv}>
                                        <div className={styles.rowDivCol}>
                                            <TextWithLabel label="First Name:" text={userObj.firstName} />
                                        </div>
                                        <div className={styles.rowDivCol}>
                                            <TextWithLabel label="Last Name:" text={userObj.lastName} />
                                        </div>
                                    </div>
                                    <TextWithLabel label="Address:" text={userObj.address} />
                                    <TextWithLabel label="Additional:" text={userObj.additional ? userObj.additional : "None"} />
                                    <div className={styles.rowDiv}>
                                        <div className={styles.rowDivCol}>
                                            <TextWithLabel label="City:" text={userObj.city} />
                                        </div>
                                        <div className={styles.rowDivCol}>
                                            <TextWithLabel label="Postal:" text={userObj.postalCode} />
                                        </div>
                                    </div>
                                    <TextWithLabel label="Phone:" text={userObj.phoneNumber} />
                                </div>
                                : null }
                                <h1 onClick={() => router.back()} className={styles.backLink}>Go back to edit</h1>
                            <MyButton onClick={() => PlaceOrder()} parentClassName={styles.button} text="Continue" />
                        </div>
                        <div className={styles.sideCon}>
                            {
                                dataState &&
                                dataState.map((data, i) => {
                                    return (
                                        <CartItem key={i}
                                            onTotalGet={(e) => totalGot(e, i)}
                                            id={data.id}
                                            size={data.size}
                                            color={data.color}
                                            quantity={data.quantity} />
                                    )
                                })}

                            <Divider />

                            <div className={styles.totalDiv}>
                                <h1>
                                    Subtotal
                                </h1>
                                <h1>
                                    {total}Rs
                                </h1>
                            </div>

                            <div className={styles.totalDiv}>
                                <h1>
                                    Shipping
                                </h1>
                                <h1>
                                    200Rs
                                </h1>
                            </div>

                            <Divider />

                            <div className={styles.totalDiv}>
                                <h1>
                                    Total
                                </h1>
                                <h1>
                                    {total + 200}Rs
                                </h1>
                            </div>

                        </div>
                    </div>
                    : <button onClick={() => getCookie()}>Retrive Data</button>}
            </main>

            <style global jsx>{`
            body {
               margin: 0px !important;
               padding: 0px !important;

            }`}</style>
        </div>

    )
}
