import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import React, { useState, useEffect } from 'react'
import Link from 'next/link'
import { Navbar, ItemCard, Divider, BackToTopButton } from '../Components/MyComponents'
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCheck,
  faTruckFast,
  faRightLeft,
  faHeadset
} from "@fortawesome/free-solid-svg-icons";

export default function Home() {
  const [dataState, setDataState] = useState([]);
  const [gotData, setGotData] = useState(false);
  useEffect(() => {
    FindProducts();
  }, []);

  function FindProducts() {
    axios.get(`http://localhost:1000/getAllProducts`).then((response) => {
      if (response.data) {
        setDataState(response.data.data);
        setGotData(true);
      }
    });
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <BackToTopButton />
        <div className={styles.infoDiv}>
          <div className={styles.infoSubDiv}>
            <div className={styles.infoDivItem}>
              <FontAwesomeIcon
                className={styles.infoDivIcon}
                icon={faCheck} />
              <h2 className={styles.infoDivText}>Quality Products</h2>
            </div>
            <div className={styles.infoDivItem}>
              <FontAwesomeIcon
                className={styles.infoDivIcon}
                icon={faTruckFast} />
              <h2 className={styles.infoDivText} style={{ fontSize: '1em' }}>Free delivery for order over 2000 rupees</h2>
            </div>
          </div>

          <div className={styles.infoSubDiv}>

            <div className={styles.infoDivItem}>
              <FontAwesomeIcon
                className={styles.infoDivIcon}
                icon={faRightLeft} />
              <h2 className={styles.infoDivText}>7-day Return</h2>
            </div>
            <div className={styles.infoDivItem}>
              <FontAwesomeIcon
                className={styles.infoDivIcon}
                icon={faHeadset} />
              <h2 className={styles.infoDivText}>24/7 Service</h2>
            </div>
          </div>

        </div>

        <Divider title="Featured Products" />

        <div className={styles.itemCon}>


          {gotData ?
              dataState.map((data, i) => {
                return (
                  <ItemCard key={i} imageSrc={data.imageSrc[0]} link={"/ItemDetail/" + data._id} title={data.name} price={data.price} sale={data.sale} priceOld={data.oldPrice} />
                )
              })
            : null}

        </div>
      </main>



      <style global jsx>{`
            body {
               margin: 0px !important;
               padding: 0px !important;

            }`}</style>
    </div>

  )
}